name: Continuous Integration
on: [push, pull_request]

jobs:
  tsc:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 18
      - name: yarn
        run: yarn --frozen-lockfile
      - name: tsc
        run: yarn tsc

  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 18
      - name: yarn
        run: yarn --frozen-lockfile
      - name: test
        run: yarn test

  deno:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: run example
        run: deno test deno
      - name: test
        run: deno test deno